### ISSUE TITLE
Auto Tracking not working on latest HDT

### ISSUE THREAD

**Issue by OSBooter** [arkein/Hearthstone-Treasury#5]
Auto tracking seems to not work with latest. All these entries are manual :(
![hearthstonedecktracker_2019-02-21_06-35-33](https://user-images.githubusercontent.com/10489079/53166294-ea192000-35a2-11e9-9aa1-97e666e35449.png)

**Comment by arkein** [comment]
@OSBooter I've released plugin v0.5.1, please test with HDT 1.8.0 or newer.

**Comment by OSBooter** [comment]
Not sure why, 
![HearthstoneDeckTracker_2019-03-13_05-25-31](https://user-images.githubusercontent.com/10489079/54267956-99b53280-4550-11e9-8d41-3fdfece0f417.png)

Still not happening.
